### PR TITLE
loader/ttf: Spaces and invalid glyphs rendering fix

### LINKED ISSUE #2687: loader/text: Invalid space width
A space's width is incorrect when it appears after a glyph with kerning applied:

```
auto text = tvg::Text::gen();
text->font("Arial", 80);
text->text("  Te s   t \xe4\xb8\x8d !");
text->fill(255, 255, 255);
canvas->push(std::move(text));
```

Output:

Expected output:

### PR DESCRIPTION
**Pull request by lpogic**
Whitespace is processed as valid glyph without an outline.
If for any reason an invalid glyph is found in text, it will now be skipped when rendering (instead of increasing offset by last valid glyph advance).

Closes #2687

### CODE REVIEW

File: src/loaders/ttf/tvgTtfReader.cpp [hunk 1]
```diff
@@ -389,10 +389,11 @@ uint32_t TtfReader::glyph(uint32_t codepoint, TtfGlyphMetrics& gmetrics)
     auto glyph = this->glyph(codepoint);
     if (glyph == INVALID_GLYPH) {
         TVGERR("TTF", "invalid glyph id, codepoint(0x%x)", codepoint);
-        return INVALID_GLYPH;
+    } else if(!glyphMetrics(glyph, gmetrics)) {
```
Comment (hermet) [inline src/loaders/ttf/tvgTtfReader.cpp:392]: Considering your first commit, it looks you don't need to change the code in glyph().
Could you please squash commits into one to make it clearly visible?

**Review by hermet — COMMENTED** [review]
@lpogic Thanks. Could you please squash the commits and include the PR messages in the commit message so that we can track the history through the pure Git system?

**Comment by lpogic** [comment]
Dear @hermet. I tried to implement the recommendations in the review, but I'm afraid I only made things worse. If so, I'll make a new PR and work on my git level.

**Comment by lpogic** [comment]
I think it should be better now

File: src/loaders/ttf/tvgTtfReader.cpp [hunk 2]
```diff
@@ -389,10 +389,11 @@ uint32_t TtfReader::glyph(uint32_t codepoint, TtfGlyphMetrics& gmetrics)
     auto glyph = this->glyph(codepoint);
     if (glyph == INVALID_GLYPH) {
         TVGERR("TTF", "invalid glyph id, codepoint(0x%x)", codepoint);
-        return INVALID_GLYPH;
```
Comment (hermet) [inline src/loaders/ttf/tvgTtfReader.cpp:392]: @lpogic It doesn't seem necessary to change the `glyph()` function. I'd like to ask you to retain the original code unless this is needed for your fix. Could you please double-check this?

Comment (lpogic) [reply src/loaders/ttf/tvgTtfReader.cpp:392]: This change is not essential and was just to make debugging easier. I will revert it soon.

Comment (hermet) [reply src/loaders/ttf/tvgTtfReader.cpp:392]: Coud you please apply this code?
```
if (glyph == INVALID_GLYPH || !glyphMetrics(glyph, gmetrics)) {
        TVGERR("TTF", "invalid glyph id, codepoint(0x%x)", codepoint);
        return INVALID_GLYPH;
}
return glyph;
```

**Review by hermet — APPROVED** [review]
